name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: |
        echo "$KUBECONFIG_CONTENT" | base64 --decode > /tmp/kubeconfig
        export KUBECONFIG=/tmp/kubeconfig
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}

    - name: Verify Kubernetes context
      run: kubectl config current-context

    - name: Deploy to AKS
      run: kubectl apply -f deployment.yaml
