name: Update AKS Deployment

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  update-aks:
    runs-on: ubuntu-latest
    environment: n8n_bs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Reconstruct KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_PART1 }}${{ secrets.KUBECONFIG_PART2 }}${{ secrets.KUBECONFIG_PART3 }}" > $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Pull latest n8n Docker image
        run: docker pull n8nio/n8n

      - name: Update AKS deployment
        run: |
          kubectl set image deployment/n8n-deployment n8n=n8nio/n8n:latest --record
        env:
          KUBECONFIG: $HOME/.kube/config
