name: Check Terraform State

on:
  workflow_dispatch:

jobs:
  check-state:
    environment: n8n_bs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Subscription ID
        id: azure-vars
        run: |
          SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          echo "subscription_id=$SUBSCRIPTION_ID" >> $GITHUB_OUTPUT

      - name: Terraform Init with Remote Backend
        run: |
          echo "Initializing Terraform with Azure Storage backend..."
          terraform init \
            -backend-config="storage_account_name=${{ secrets.TERRAFORM_BACKEND_STORAGE_ACCOUNT }}" \
            -backend-config="access_key=${{ secrets.TERRAFORM_BACKEND_ACCESS_KEY }}"
        env:
          ARM_USE_CLI: true
          ARM_SUBSCRIPTION_ID: ${{ steps.azure-vars.outputs.subscription_id }}

      - name: Show Terraform State
        run: |
          echo "==================== TERRAFORM STATE ===================="
          terraform state list
          echo ""
          echo "==================== STATE DETAILS ===================="
          echo "Number of resources in state: $(terraform state list | wc -l)"
          echo ""
          echo "If you see resources listed above, the import was successful!"
          echo "You can now run 'Apply Python Task Runner - External Mode' workflow."
