name: Check Required Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    environment: n8n_bs
    runs-on: ubuntu-latest
    steps:
      - name: Check if Required Secrets Exist
        run: |
          echo "==================== CHECKING REQUIRED SECRETS ===================="

          # Check ADMINISTRATOR_LOGIN_PASSWORD
          if [ -z "${{ secrets.TF_VAR_ADMINISTRATOR_LOGIN_PASSWORD }}" ]; then
            echo "❌ TF_VAR_ADMINISTRATOR_LOGIN_PASSWORD is NOT set"
            EXIT_CODE=1
          else
            echo "✅ TF_VAR_ADMINISTRATOR_LOGIN_PASSWORD is set (length: ${#TF_VAR_ADMINISTRATOR_LOGIN_PASSWORD} characters)"
            EXIT_CODE=0
          fi

          # Check POSTGRES_PASSWORD
          if [ -z "${{ secrets.TF_VAR_POSTGRES_PASSWORD }}" ]; then
            echo "❌ TF_VAR_POSTGRES_PASSWORD is NOT set"
            EXIT_CODE=1
          else
            echo "✅ TF_VAR_POSTGRES_PASSWORD is set (length: ${#TF_VAR_POSTGRES_PASSWORD} characters)"
          fi

          echo ""
          echo "==================== SUMMARY ===================="
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ All required secrets are configured!"
            echo ""
            echo "You can now run the 'Apply Python Task Runner - External Mode' workflow."
          else
            echo "❌ Some secrets are missing!"
            echo ""
            echo "Please set the missing secrets in GitHub:"
            echo "1. Go to Settings → Secrets and variables → Actions"
            echo "2. Click 'New repository secret' or check Environment: n8n_bs"
            echo "3. Add the missing secrets"
            exit 1
          fi
        env:
          TF_VAR_ADMINISTRATOR_LOGIN_PASSWORD: ${{ secrets.TF_VAR_ADMINISTRATOR_LOGIN_PASSWORD }}
          TF_VAR_POSTGRES_PASSWORD: ${{ secrets.TF_VAR_POSTGRES_PASSWORD }}
