name: Upgrade n8n to Next

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows for manual triggering from the GitHub Actions UI

jobs:
  upgrade-n8n:
    environment: n8n_bs
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set kubectl context for the AKS cluster
        run: |
          az aks get-credentials --resource-group n8n_bs --name n8nAKScluster --overwrite-existing

      - name: Update n8n deployment image to :next
        run: |
          echo "Updating n8n deployment image in namespace 'n8n'"
          kubectl set image deployment/n8n n8n=n8nio/n8n:next --record -n n8n
          kubectl rollout status deployment/n8n -n n8n
          
