name: Reset PostgreSQL Password and Show Value

on:
  workflow_dispatch:

jobs:
  reset-password:
    environment: n8n_bs
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Reset PostgreSQL Password
        run: |
          echo "==================== RESETTING POSTGRESQL PASSWORD ===================="

          # Get PostgreSQL server info
          POSTGRES_SERVER=$(az postgres flexible-server list --resource-group n8n_bs --query '[0].name' -o tsv)
          echo "PostgreSQL Server: $POSTGRES_SERVER"

          # Generate a strong random password
          NEW_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)

          echo "Generated new password (SAVE THIS - it will only be shown once!)"
          echo ""
          echo "╔════════════════════════════════════════════════════════════╗"
          echo "║  NEW PASSWORD: $NEW_PASSWORD  ║"
          echo "╚════════════════════════════════════════════════════════════╝"
          echo ""

          # Reset the password in Azure
          echo "Updating PostgreSQL server password..."
          az postgres flexible-server update \
            --resource-group n8n_bs \
            --name $POSTGRES_SERVER \
            --admin-password "$NEW_PASSWORD" \
            --output table

          echo ""
          echo "✅ PostgreSQL password has been reset successfully!"
          echo ""
          echo "==================== NEXT STEPS ===================="
          echo ""
          echo "Copy the password above and use it to set GitHub secrets."
          echo ""
          echo "Since you only have GitHub Actions CLI access, run the deployment workflow"
          echo "and it will PROMPT you for the passwords during terraform apply."
          echo ""
          echo "OR, if you have access to the repository settings:"
          echo "1. Go to: https://github.com/xliberty2008x/n8n_azure/settings/secrets/actions"
          echo "2. Click on Environment: n8n_bs"
          echo "3. Add/Update these secrets with the password shown above:"
          echo "   - TF_VAR_ADMINISTRATOR_LOGIN_PASSWORD"
          echo "   - TF_VAR_POSTGRES_PASSWORD"
          echo ""
          echo "Password to use: $NEW_PASSWORD"
